WATCHSTOCKLIST = [
    {"name": "Reliance Industries", "tradingsymbol": "RELIANCE-EQ", "symboltoken": "2885", "exchange": "NSE"},
    {"name": "HDFC Bank", "tradingsymbol": "HDFCBANK-EQ", "symboltoken": "1333", "exchange": "NSE"},
    {"name": "ICICI Bank", "tradingsymbol": "ICICIBANK-EQ", "symboltoken": "4963", "exchange": "NSE"},
    {"name": "Infosys", "tradingsymbol": "INFY-EQ", "symboltoken": "1594", "exchange": "NSE"},
    {"name": "TCS", "tradingsymbol": "TCS-EQ", "symboltoken": "11536", "exchange": "NSE"},
    {"name": "Larsen & Toubro", "tradingsymbol": "LT-EQ", "symboltoken": "2937", "exchange": "NSE"},
    {"name": "Axis Bank", "tradingsymbol": "AXISBANK-EQ", "symboltoken": "5900", "exchange": "NSE"},
    {"name": "Kotak Mahindra Bank", "tradingsymbol": "KOTAKBANK-EQ", "symboltoken": "1922", "exchange": "NSE"},
    {"name": "Hindustan Unilever", "tradingsymbol": "HINDUNILVR-EQ", "symboltoken": "1394", "exchange": "NSE"},
    {"name": "ITC", "tradingsymbol": "ITC-EQ", "symboltoken": "1660", "exchange": "NSE"},
    {"name": "Bharti Airtel", "tradingsymbol": "BHARTIARTL-EQ", "symboltoken": "27127", "exchange": "NSE"},
    {"name": "State Bank of India", "tradingsymbol": "SBIN-EQ", "symboltoken": "3045", "exchange": "NSE"},
    {"name": "Maruti Suzuki", "tradingsymbol": "MARUTI-EQ", "symboltoken": "3351", "exchange": "NSE"},
    {"name": "HCL Technologies", "tradingsymbol": "HCLTECH-EQ", "symboltoken": "7229", "exchange": "NSE"},
    {"name": "NTPC", "tradingsymbol": "NTPC-EQ", "symboltoken": "2972", "exchange": "NSE"},
    {"name": "Mahindra & Mahindra", "tradingsymbol": "M&M-EQ", "symboltoken": "2031", "exchange": "NSE"},
    {"name": "Tata Steel", "tradingsymbol": "TATASTEEL-EQ", "symboltoken": "3499", "exchange": "NSE"},
    {"name": "Titan", "tradingsymbol": "TITAN-EQ", "symboltoken": "3506", "exchange": "NSE"},
    {"name": "Bajaj Finserv", "tradingsymbol": "BAJAJFINSV-EQ", "symboltoken": "16675", "exchange": "NSE"},
    {"name": "Power Grid Corp", "tradingsymbol": "POWERGRID-EQ", "symboltoken": "14977", "exchange": "NSE"},
    {"name": "Nestle India", "tradingsymbol": "NESTLEIND-EQ", "symboltoken": "17963", "exchange": "NSE"},
    {"name": "Asian Paints", "tradingsymbol": "ASIANPAINT-EQ", "symboltoken": "236", "exchange": "NSE"},
    {"name": "Tech Mahindra", "tradingsymbol": "TECHM-EQ", "symboltoken": "13538", "exchange": "NSE"},
    {"name": "IndusInd Bank", "tradingsymbol": "INDUSINDBK-EQ", "symboltoken": "5258", "exchange": "NSE"},
    {"name": "Wipro", "tradingsymbol": "WIPRO-EQ", "symboltoken": "3787", "exchange": "NSE"},
    {"name": "HDFC Life", "tradingsymbol": "HDFCLIFE-EQ", "symboltoken": "4670", "exchange": "NSE"},
    {"name": "Tata Motors", "tradingsymbol": "TATAMOTORS-EQ", "symboltoken": "3456", "exchange": "NSE"}
]
