# utils/stock_list.py
WATCHSTOCKLIST = [
    {"name": "Reliance Industries",      "exchange": "NSE", "tradingsymbol": "RELIANCE-EQ"},
    {"name": "HDFC Bank",                "exchange": "NSE", "tradingsymbol": "HDFCBANK-EQ"},
    {"name": "ICICI Bank",               "exchange": "NSE", "tradingsymbol": "ICICIBANK-EQ"},
    {"name": "Infosys",                  "exchange": "NSE", "tradingsymbol": "INFY-EQ"},
    {"name": "TCS",                      "exchange": "NSE", "tradingsymbol": "TCS-EQ"},
    {"name": "Larsen & Toubro",          "exchange": "NSE", "tradingsymbol": "LT-EQ"},
    {"name": "Axis Bank",                "exchange": "NSE", "tradingsymbol": "AXISBANK-EQ"},
    {"name": "Kotak Mahindra Bank",      "exchange": "NSE", "tradingsymbol": "KOTAKBANK-EQ"},
    {"name": "Hindustan Unilever",       "exchange": "NSE", "tradingsymbol": "HINDUNILVR-EQ"},
    {"name": "ITC",                      "exchange": "NSE", "tradingsymbol": "ITC-EQ"},
    {"name": "Bharti Airtel",            "exchange": "NSE", "tradingsymbol": "BHARTIARTL-EQ"},
    {"name": "State Bank of India",      "exchange": "NSE", "tradingsymbol": "SBIN-EQ"},
    {"name": "Maruti Suzuki",            "exchange": "NSE", "tradingsymbol": "MARUTI-EQ"},
    {"name": "HCL Technologies",         "exchange": "NSE", "tradingsymbol": "HCLTECH-EQ"},
    {"name": "NTPC",                     "exchange": "NSE", "tradingsymbol": "NTPC-EQ"},
    {"name": "Mahindra & Mahindra",      "exchange": "NSE", "tradingsymbol": "M&M-EQ"},
    {"name": "Tata Steel",               "exchange": "NSE", "tradingsymbol": "TATASTEEL-EQ"},
    {"name": "Titan",                    "exchange": "NSE", "tradingsymbol": "TITAN-EQ"},
    {"name": "Bajaj Finserv",            "exchange": "NSE", "tradingsymbol": "BAJAJFINSV-EQ"},
    {"name": "Power Grid Corp",          "exchange": "NSE", "tradingsymbol": "POWERGRID-EQ"},
    {"name": "Nestle India",             "exchange": "NSE", "tradingsymbol": "NESTLEIND-EQ"},
    {"name": "Asian Paints",             "exchange": "NSE", "tradingsymbol": "ASIANPAINT-EQ"},
    {"name": "Tech Mahindra",            "exchange": "NSE", "tradingsymbol": "TECHM-EQ"},
    {"name": "IndusInd Bank",            "exchange": "NSE", "tradingsymbol": "INDUSINDBK-EQ"},
    {"name": "Wipro",                    "exchange": "NSE", "tradingsymbol": "WIPRO-EQ"},
    {"name": "Tata Motors",              "exchange": "NSE", "tradingsymbol": "TATAMOTORS-EQ"},
]
